meta-openembedded: zeromq: Update to version 4.1.5.
Added PACKAGECONFIG to use libsodium instead of builtin tweetnacl.

Compiling with current master led to:

| ../zeromq-4.1.5/src/ctx.cpp:50:28: fatal error: randombytes.h: No such file or directory
|  #   include "randombytes.h"
|                             ^
| compilation terminated.
| Makefile:2573: recipe for target 'src/libzmq_la-ctx.lo' failed
| make[1]: *** [src/libzmq_la-ctx.lo] Error 1
| make[1]: *** Waiting for unfinished jobs....
| In file included from ../zeromq-4.1.5/src/curve_client.cpp:41:0:
| ../zeromq-4.1.5/src/curve_client.hpp:39:31: fatal error: tweetnacl_base.h: No such file or directory
|  #   include "tweetnacl_base.h"
|                                ^
| compilation terminated.

Using external libsodium works around this. The default for PACKAGECONFIG is
set to use external libsodium so the recipe builds.

(From meta-openembedded rev: d0c4bdc2fa5b3f4d00d5c1160088197114deb4d5)

Signed-off-by: Philip Balister <philip@balister.org>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>